sudo: required
services:
  - docker
language: bash
env:
  global:
    - IMAGE_NAME=simonqbs/arm-mosquitto

before_install:
  - echo $(docker -v)
  - apt-get update
  - apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - echo $(docker -v)
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script: 
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - VCS_REF=$(git rev-parse --short HEAD)
  - docker build --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=$BUILD_DATE -t $IMAGE_NAME:build .

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag $IMAGE_NAME:build $IMAGE_NAME:latest
      docker push $IMAGE_NAME:latest
    fi  
